import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import { Layout } from "antd";
import Sider from "antd/es/layout/Sider";

import AppHeader from "./components/AppHeader";
import AppSideMenu from "./components/AppSideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AntdRegistry>
        <Layout> 
          <AppHeader />
          <Layout hasSider>
            <Sider
                theme="light"
                style={{
                  position: "fixed",
                  top: "64px",
                  left: 0,
                  borderRight: "1px solid #f1f1f1",
                  height: "calc(100vh - 64px)",
                }}
              >
              <AppSideMenu />
            </Sider>
          </Layout>
          {children}

        </Layout>
       
        
      </AntdRegistry>
      </body>
    </html>
  );
}
