import type { Metadata } from "next";
import {  Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Layout } from "antd";
import AppHeader from "./components/AppHeader";
import AppSideMenu from "./components/AppSideMenu";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Sider from "antd/es/layout/Sider";
import {Content} from "antd/es/layout/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout style={{ minHeight: "100vh" }}>
            <AppHeader />
            <Layout hasSider>
              <Sider
                width={250}
                style={{
                  background: "#fff",
                  position: "fixed",
                  left: 0,
                  top: 64,
                  bottom: 0,
                }}>
                <AppSideMenu />
              </Sider>
            </Layout>
            <Layout style={{ marginLeft: 250 }}>
              <Content style={{ padding: "24px", minHeight: "100vh" }}>
                {children}
              </Content>
      
            </Layout>
          </Layout>

        </AntdRegistry>
      </body>
    </html>
  );
}
